# Generated by Django 5.1.6 on 2025-02-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grievances',
            new_name='Grievances_model',
        ),
        migrations.RenameField(
            model_name='institution_model',
            old_name='institution_phone',
            new_name='institution_contact',
        ),
        migrations.RenameField(
            model_name='semester_model',
            old_name='course_id',
            new_name='sem_id',
        ),
        migrations.RenameField(
            model_name='semester_model',
            old_name='semester_name',
            new_name='subject_code',
        ),
        migrations.RenameField(
            model_name='subject_model',
            old_name='subject_code',
            new_name='semester_name',
        ),
        migrations.RemoveField(
            model_name='subject_model',
            name='sem_id',
        ),
        migrations.RemoveField(
            model_name='subject_model',
            name='subject_credit',
        ),
        migrations.RemoveField(
            model_name='subject_model',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='semester_model',
            name='subject_credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semester_model',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject_model',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course_model'),
        ),
    ]
