# Generated by Django 5.1.6 on 2025-02-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notification_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subject_model',
            new_name='sem_model',
        ),
        migrations.RenameModel(
            old_name='semester_model',
            new_name='Subject_models',
        ),
    ]
