# Generated by Django 5.1.6 on 2025-02-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_subject_model_sem_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='SEMID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sem_model'),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subject_models'),
        ),
        migrations.AlterField(
            model_name='subject_models',
            name='sem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sem_model'),
        ),
    ]
