# Generated by Django 5.1.6 on 2025-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_model_semid_alter_exam_model_subject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_model',
            name='assignment_outof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark_model',
            name='assignmentmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark_model',
            name='mark_outof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark_model',
            name='seminar_outof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark_model',
            name='seminarmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mark_model',
            name='weightage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
