# Generated by Django 5.1.6 on 2025-03-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feedback_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_models',
            name='FACULITY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty_model'),
        ),
    ]
