
from django.urls import include, path

from .views import *

urlpatterns = [
   path('', Login.as_view(), name='login'),
   path('adminhome', Adminhome.as_view(), name='adminhome'),
   path('institution_details', institutiondetails.as_view(), name='institution_details'),
   path('manage_courses', managecourses.as_view(), name='manage_courses'),
   path('manage_student', managestudents.as_view(), name='manage_student'),
   path('manage_faculties', managefaculty.as_view(), name='manage_faculties'),
   path('manage_program', manageprograms.as_view(), name='manage_program'),
   path('notification', notification.as_view(), name='notification'),
   path('view_addstudents', viewaddstudent.as_view(), name='view_addstudents'),
   path('view_editstudents/<int:id>', vieweditstudents.as_view(), name='view_editstudents'),
   path('view_institution_details', view_institutiondetails.as_view(), name='view_institution_details'),
   path('viewadd_managecourses', viewaddmanagecourses.as_view(), name='viewadd_managecourses'),
   path('viewedit_managecourses', vieweditmanagecourses.as_view(), name='viewedit_managecourses'),
   path('viewadd_managefaculties', viewaddmanagefaculty.as_view(), name='viewadd_managefaculties'),
   path('viewedit_managefaculties/<int:id>', vieweditmanagefaculty.as_view(), name='viewedit_managefaculties'),
   path('viewadd_manageprogram', viewaddmanageprogram.as_view(), name='viewadd_manageprogram'),
   path('viewedit_manageprogram', vieweditmanageprogram.as_view(), name='viewedit_manageprogram'),
   path('componenty and weightage', componentsandweightage.as_view(), name='componenty and weightage'),
   path('entermark', entermark.as_view(), name='entermark'),
   path('facultyfunction', facultyfunction.as_view(), name='facultyfunction'),
   path('facultyhome', facultyhome.as_view(), name='facultyhome'),
   path('report', report.as_view(), name='report'),
   path('viewreport', viewreport.as_view(), name='viewreport'),
   path('viewnotification', viewnotification.as_view(), name='viewnotification'),
   path('deleteint/<int:id>', DeleteInst.as_view(), name='deleteint'),
   path('editint/<int:id>', EditInst.as_view(), name='editint'),
   path('deletepgm/<int:id>', deleteprgm.as_view(), name='deletepgm'),
   path('editpgm/<int:id>', editprgm.as_view(), name='editpgm'),
   path('deletecourse/<int:id>', deletecourse.as_view(), name='deletecourse'),
   path('editcourse/<int:id>', editcourse.as_view(), name='editcourse'),
   path('deletefac/<int:id>', DeleteFac.as_view(), name='deletefac'),
   path('deletestu/<int:id>', deletestudent.as_view(), name='deletestu'),
   path('notification', notification.as_view(), name='notification'),
   path('managesemester', Manage_Semester.as_view(), name='managesemester'),
   path('addsemester', Add_Semester.as_view(), name='addsemester'),
   path('deletesemester/<int:id>', Delete_Semester.as_view(), name='deletesemester'),
]
